#!/usr/bin/env python3
# (AI-assisted)
# Generates no-op Mips2C::<game>::<name>::link() definitions for every game except Jak 1, from
# the declarations in game/mips2c/mips2c_table.cpp. The 3DS build only compiles the Jak 1 mips2c
# functions; the table still references the other games.
#
# TEMPORARY: remove once mips2c_table.cpp only references the games that are built
# (see docs/3ds-port/3ds_build.md, "changes needed in runtime files").
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
keep = {"jak1"}
out = ["// Generated by platform/3ds/tools/gen_mips2c_stubs.py. Do not edit.", "namespace Mips2C {"]
game = None
seen = set()
for line in open(src):
    m = re.match(r"^namespace (jak\w+) \{\s*$", line)
    if m:
        game = m.group(1)
        continue
    if game and re.match(r"^\}\s*(//.*)?$", line):
        game = None
        continue
    if game and game not in keep:
        m = re.match(r"^\s*namespace (\w+) \{ extern void link\(\); \}", line)
        if m and (game, m.group(1)) not in seen:
            seen.add((game, m.group(1)))
            out.append(f"namespace {game} {{ namespace {m.group(1)} {{ void link() {{}} }} }}")
out.append("}  // namespace Mips2C")
text = "\n".join(out) + "\n"
try:
    if open(dst).read() == text:
        sys.exit(0)
except FileNotFoundError:
    pass
open(dst, "w").write(text)
