// (AI-assisted) Generated by test/mips2c_native/goalc_ref/extract.py: do not edit.
// GOAL module collide-func compiled to C by goalc (--instruction-set c, module hash
// 0xe3b4dcb7659753fb), only the functions the tests use, and the module's main segment.
#include "goal_c_ops.h"
#include "goalc_ref.h"

_Static_assert(GOALC_ABI_VERSION == 2, "regenerate the fixtures (extract.py)");

static int32_t gc_sym_offsets[12];
static uint32_t gc_seg_base[3];
static const char* const gc_sym_names[12] = {
    "pc-port-raw-ray-sphere-implementation",
    "ray-sphere-intersect",
    "vector-normalize!",
    "vector+*!",
    "raw-ray-sphere-intersect",
    "ray-circle-intersect",
    "ray-cylinder-intersect",
    "ray-plane-intersect",
    "__pc-get-mips2c",
    "collide-do-primitives",
    "moving-sphere-triangle-intersect",
    "moving-sphere-sphere-intersect",
};

static u64 gc_f1(u64 a0, u64 a1, u64 a2) {
  u8* const gc_mb = goalc_mem;
  const u64 gc_stl = (u32)goalc_st;
  const u64 gc_sb = GC_SEG(0);
  u64 r0 = 0;
  u64 r1 = 0;
  u64 r2 = 0;
  u64 r3 = 0;
  u64 r4 = 0;
  u64 r5 = 0;
  u64 r6 = 0;
  u64 r7 = 0;
  u64 r8 = 0;
  u64 r9 = 0;
  float r10 = 0;
  float r11 = 0;
  u64 r12 = 0;
  u64 r13 = 0;
  v128 r14 = {0};
  v128 r15 = {0};
  v128 r16 = {0};
  v128 r17 = {0};
  v128 r18 = {0};
  v128 r19 = {0};
  v128 r20 = {0};
  v128 r21 = {0};
  v128 r22 = {0};
  v128 r23 = {0};
  v128 r24 = {0};
  v128 r25 = {0};
  u64 r26 = 0;
  u64 r27 = 0;
  float r28 = 0;
  v128 r29 = {0};
  v128 r30 = {0};
  v128 r31 = {0};
  v128 r32 = {0};
  u64 r33 = 0;
  u64 r34 = 0;
  float r35 = 0;
  v128 r36 = {0};
  v128 r37 = {0};
  v128 r38 = {0};
  v128 r39 = {0};
  v128 r40 = {0};
  u64 r41 = 0;
  u64 r42 = 0;
  u64 r43 = 0;
  u64 r44 = 0;
  u64 r45 = 0;
  u64 r46 = 0;
  u64 r47 = 0;
  u64 r48 = 0;
  v128 r49 = {0};
  u64 r50 = 0;
  u64 r51 = 0;
  u64 r52 = 0;
  u64 r53 = 0;
  u64 r54 = 0;
  u64 r55 = 0;
  u64 r56 = 0;
  u64 r57 = 0;
  u64 r58 = 0;
  u64 r59 = 0;
  u64 r60 = 0;
  u64 r61 = 0;
  u64 r62 = 0;
  u64 r63 = 0;
  u64 r64 = 0;
  u64 r65 = 0;
  u64 r66 = 0;
  u64 r67 = 0;
  u64 r68 = 0;
  float r69 = 0;
  u64 r70 = 0;
  u64 r71 = 0;
  u64 r72 = 0;
  v128 r73 = {0};
  v128 r74 = {0};
  v128 r75 = {0};
  v128 r76 = {0};
  u64 r77 = 0;
  u64 r78 = 0;
  u64 r79 = 0;
  u64 r80 = 0;
  u64 r81 = 0;
  u64 r82 = 0;
  u64 r83 = 0;
  v128 r84 = {0};
  u64 r85 = 0;
  u64 r86 = 0;
  u64 r87 = 0;
  u64 r88 = 0;
  u64 r89 = 0;
  u64 r90 = 0;
  u64 r91 = 0;
  u64 r92 = 0;
  float r93 = 0;
  float r94 = 0;
  u64 r95 = 0;
  r0 = a0;
  r1 = a1;
  r2 = a2;
  r4 = r0;
  r5 = r1;
  r6 = r2;
  r15 = gc_ld_v128(gc_sb, 144 + 0);
  r16 = gc_ld_v128(r5, 0);
  r17 = gc_ld_v128(r6, 0);
  r18 = gc_g2q(r4);
  r19 = gc_vf_mul(r17, r17);
  r18 = gc_vf_mul(r18, r18);
  r21 = gc_vf_mul(r16, r16);
  r20 = gc_vf_mul(r17, r16);
  r25 = gc_vf_splat(r19, 1);
  r25 = gc_vf_add(r19, r25);
  r19 = gc_vf_blend(r19, r25, 1);
  r26 = 0x0ull;
  r27 = r26;
  r28 = gc_g2f(r27);
  r29 = gc_vf_splat(r21, 0);
  r29 = gc_vf_add(r21, r29);
  r21 = gc_vf_blend(r21, r29, 2);
  r30 = gc_vf_splat(r18, 0);
  r30 = gc_vf_sub(r21, r30);
  r21 = gc_vf_blend(r21, r30, 4);
  r31 = gc_vf_splat(r19, 2);
  r31 = gc_vf_add(r19, r31);
  r19 = gc_vf_blend(r19, r31, 1);
  r32 = gc_vf_splat(r20, 0);
  r32 = gc_vf_add(r20, r32);
  r20 = gc_vf_blend(r20, r32, 2);
  r33 = 0x0ull;
  r34 = r33;
  r35 = gc_g2f(r34);
  r36 = gc_vf_splat(r21, 2);
  r36 = gc_vf_add(r21, r36);
  r21 = gc_vf_blend(r21, r36, 2);
  r37 = gc_vf_splat(r15, 3);
  r38 = gc_vf_splat(r19, 0);
  r14 = gc_vf_div(r37, r38);
  r39 = gc_vf_splat(r20, 2);
  r39 = gc_vf_add(r20, r39);
  r20 = gc_vf_blend(r20, r39, 2);
  r10 = gc_q2f(r19);
  r40 = gc_vf_splat(r19, 0);
  r22 = gc_vf_mul(r21, r40);
  r13 = gc_q2g(r21);
  r23 = gc_vf_mul(r20, r20);
  r41 = r13;
  r42 = 0x0ull;
  r43 = gc_stl;
  if ((s64)r41 >= (s64)r42)
    goto L53;
  r44 = ((u64)(u32)(gc_stl + 8));
  r43 = r44;
L53:;
  r45 = r43;
  r11 = r10;
  r47 = gc_stl;
  if (r45 == r47)
    goto L60;
  r48 = ((u64)(u32)(gc_stl + -10));
  goto L156;
  goto L61;
L60:;
  r46 = gc_stl;
L61:;
  r49 = gc_vf_mul(r15, r14);
  r19 = gc_vf_blend(r19, r49, 8);
  r24 = gc_vf_sub(r23, r22);
  r50 = gc_stl;
  if (r11 != r35)
    goto L69;
  r51 = ((u64)(u32)(gc_stl + 8));
  r50 = r51;
L69:;
  r52 = r50;
  r7 = gc_q2g(r20);
  r54 = gc_stl;
  if (r52 == r54)
    goto L76;
  r55 = ((u64)(u32)(gc_stl + -10));
  goto L154;
  goto L77;
L76:;
  r53 = gc_stl;
L77:;
  r14 = gc_vf_splat(r24, 1);
  r14 = gc_vf_sqrt(r14);
  r56 = r7;
  r57 = 0x0ull;
  r58 = gc_stl;
  if ((s64)r56 < (s64)r57)
    goto L87;
  r59 = ((u64)(u32)(gc_stl + 8));
  r58 = r59;
L87:;
  r60 = r58;
  r8 = gc_q2g(r24);
  r62 = gc_stl;
  if (r60 == r62)
    goto L94;
  r63 = ((u64)(u32)(gc_stl + -10));
  goto L154;
  goto L95;
L94:;
  r61 = gc_stl;
L95:;
  r64 = r8;
  r65 = 0x0ull;
  r66 = gc_stl;
  if ((s64)r64 >= (s64)r65)
    goto L102;
  r67 = ((u64)(u32)(gc_stl + 8));
  r66 = r67;
L102:;
  r68 = r66;
  r69 = gc_ld_f32(gc_sb, 160 + 0);
  r71 = gc_stl;
  if (r68 == r71)
    goto L109;
  r72 = ((u64)(u32)(gc_stl + -10));
  goto L154;
  goto L110;
L109:;
  r70 = gc_stl;
L110:;
  r73 = gc_vf_splat(r19, 0);
  r21 = gc_vf_add(r20, r73);
  r9 = gc_q2g(r21);
  r21 = gc_vf_mul(r21, r21);
  r74 = gc_vf_mul(r15, r14);
  r24 = gc_vf_blend(r24, r74, 8);
  r21 = gc_vf_sub(r24, r21);
  r75 = gc_vf_splat(r24, 3);
  r75 = gc_vf_add(r20, r75);
  r24 = gc_vf_blend(r24, r75, 2);
  r12 = gc_q2g(r21);
  r76 = gc_vf_splat(r19, 3);
  r76 = gc_vf_mul(r24, r76);
  r24 = gc_vf_blend(r24, r76, 2);
  r77 = r9;
  r78 = r12;
  r79 = r77;
  r79 = r79 & r78;
  r80 = 0x0ull;
  r81 = gc_stl;
  if ((s64)r79 >= (s64)r80)
    goto L134;
  r82 = ((u64)(u32)(gc_stl + 8));
  r81 = r82;
L134:;
  r83 = r81;
  r84 = gc_vf_splat(r24, 1);
  r19 = gc_vf_sub(r15, r84);
  r86 = gc_stl;
  if (r83 == r86)
    goto L142;
  r87 = ((u64)(u32)(gc_stl + -10));
  goto L154;
  goto L143;
L142:;
  r85 = gc_stl;
L143:;
  r88 = ((u64)(u32)(gc_stl + 8));
  r89 = r88;
  r28 = gc_q2f(r19);
  r91 = gc_stl;
  if (r89 == r91)
    goto L152;
  r92 = ((u64)(u32)(gc_stl + -10));
  goto L156;
  goto L153;
L152:;
  r90 = gc_stl;
L153:;
L154:;
  r93 = gc_ld_f32(gc_sb, 164 + 0);
  r28 = r93;
L156:;
  r94 = r28;
  r95 = gc_f2g(r94);
  r3 = r95;
  return r3;
}

static u64 gc_f2(u64 a0, u64 a1, u64 a2, u64 a3) {
  u8* const gc_mb = goalc_mem;
  const u64 gc_stl = (u32)goalc_st;
  u64 r0 = 0;
  u64 r1 = 0;
  u64 r2 = 0;
  u64 r3 = 0;
  u64 r4 = 0;
  u64 r5 = 0;
  u64 r6 = 0;
  u64 r7 = 0;
  u64 r8 = 0;
  v128 r9 = {0};
  v128 r10 = {0};
  u64 r11 = 0;
  u64 r12 = 0;
  u64 r13 = 0;
  u64 r14 = 0;
  u64 r15 = 0;
  u64 r16 = 0;
  u64 r17 = 0;
  u64 r18 = 0;
  u64 r19 = 0;
  u64 r20 = 0;
  u64 r21 = 0;
  u64 gc_stack[4] __attribute__((aligned(16)));
  r0 = a0;
  r1 = a1;
  r2 = a2;
  r3 = a3;
  r5 = r0;
  r6 = r1;
  r7 = r2;
  r8 = r3;
  r9 = gc_ld_v128(r5, 0);
  r10 = gc_ld_v128(r7, 0);
  r9 = gc_vf_sub(r9, r10);
  r10 = gc_ld_v128(r6, 0);
  r11 = gc_goal_ptr(&gc_stack[0]);
  r12 = gc_goal_ptr(&gc_stack[2]);
  r13 = r11;
  r14 = r12;
  gc_st_v128(r13, 0, r9);
  gc_st_v128(r14, 0, r10);
  r15 = gc_ld_u32(gc_stl, GC_SYMOFF(0));
  r17 = r8;
  r18 = r13;
  r19 = r14;
  r20 = r15;
  r16 = ((u64(*)(u64, u64, u64))gc_fn(r20))(r17, r18, r19);
  r21 = r16;
  r4 = r21;
  return r4;
}

static u64 gc_f4(u64 a0, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5, u64 a6) {
  u8* const gc_mb = goalc_mem;
  const u64 gc_stl = (u32)goalc_st;
  const u64 gc_sb = GC_SEG(0);
  u64 r0 = 0;
  u64 r1 = 0;
  u64 r2 = 0;
  u64 r3 = 0;
  u64 r4 = 0;
  u64 r5 = 0;
  u64 r6 = 0;
  u64 r7 = 0;
  u64 r8 = 0;
  u64 r9 = 0;
  u64 r10 = 0;
  u64 r11 = 0;
  u64 r12 = 0;
  u64 r13 = 0;
  u64 r14 = 0;
  float r15 = 0;
  u64 r16 = 0;
  u64 r17 = 0;
  u64 r18 = 0;
  u64 r19 = 0;
  u64 r20 = 0;
  u64 r21 = 0;
  v128 r22 = {0};
  v128 r23 = {0};
  v128 r24 = {0};
  v128 r25 = {0};
  v128 r26 = {0};
  v128 r27 = {0};
  v128 r28 = {0};
  v128 r29 = {0};
  v128 r30 = {0};
  v128 r31 = {0};
  v128 r32 = {0};
  v128 r33 = {0};
  v128 r34 = {0};
  v128 r35 = {0};
  v128 r36 = {0};
  v128 r37 = {0};
  v128 r38 = {0};
  v128 r39 = {0};
  v128 r40 = {0};
  v128 r41 = {0};
  v128 r42 = {0};
  v128 r43 = {0};
  u64 r44 = 0;
  u64 r45 = 0;
  u64 r46 = 0;
  u64 r47 = 0;
  u64 r48 = 0;
  u64 r49 = 0;
  u64 r50 = 0;
  u64 r51 = 0;
  u64 r52 = 0;
  u64 r53 = 0;
  u64 r54 = 0;
  u64 r55 = 0;
  u64 r56 = 0;
  u64 r57 = 0;
  u64 r58 = 0;
  u64 r59 = 0;
  u64 r60 = 0;
  u64 r61 = 0;
  u64 r62 = 0;
  u64 r63 = 0;
  u64 r64 = 0;
  u64 r65 = 0;
  u64 r66 = 0;
  u64 r67 = 0;
  u64 r68 = 0;
  u64 r69 = 0;
  u64 r70 = 0;
  u64 r71 = 0;
  u64 r72 = 0;
  u64 r73 = 0;
  u64 r74 = 0;
  float r75 = 0;
  float r76 = 0;
  u64 r77 = 0;
  u64 r78 = 0;
  u64 r79 = 0;
  u64 r80 = 0;
  u64 r81 = 0;
  u64 r82 = 0;
  u64 r83 = 0;
  u64 r84 = 0;
  v128 r85 = {0};
  v128 r86 = {0};
  v128 r87 = {0};
  u64 r88 = 0;
  u64 r89 = 0;
  u64 r90 = 0;
  u64 r91 = 0;
  u64 r92 = 0;
  v128 r93 = {0};
  u64 r94 = 0;
  u64 r95 = 0;
  u64 r96 = 0;
  u64 r97 = 0;
  u64 r98 = 0;
  u64 r99 = 0;
  u64 r100 = 0;
  u64 r101 = 0;
  u64 r102 = 0;
  u64 r103 = 0;
  u64 r104 = 0;
  u64 r105 = 0;
  u64 r106 = 0;
  u64 r107 = 0;
  u64 r108 = 0;
  u64 r109 = 0;
  float r110 = 0;
  u64 r111 = 0;
  u64 gc_stack[4] __attribute__((aligned(16)));
  r0 = a0;
  r1 = a1;
  r2 = a2;
  r3 = a3;
  r4 = a4;
  r5 = a5;
  r6 = a6;
  r8 = r0;
  r9 = r1;
  r10 = r2;
  r11 = r3;
  r12 = r4;
  r13 = r5;
  r14 = r6;
  r23 = gc_ld_v128(r8, 0);
  r25 = gc_ld_v128(r10, 0);
  r28 = gc_vf_sub(r23, r25);
  r24 = gc_ld_v128(r9, 0);
  r26 = gc_ld_v128(r11, 0);
  r27 = gc_g2q(r13);
  r29 = gc_vf_mul(r28, r26);
  r30 = gc_vf_mul(r24, r26);
  r36 = gc_vf_splat(r29, 0);
  r36 = gc_vf_add(r29, r36);
  r29 = gc_vf_blend(r29, r36, 2);
  r37 = gc_vf_splat(r30, 0);
  r37 = gc_vf_add(r30, r37);
  r30 = gc_vf_blend(r30, r37, 2);
  r38 = gc_vf_splat(r29, 2);
  r38 = gc_vf_add(r29, r38);
  r29 = gc_vf_blend(r29, r38, 2);
  r39 = gc_vf_splat(r30, 2);
  r39 = gc_vf_add(r30, r39);
  r30 = gc_vf_blend(r30, r39, 2);
  r40 = gc_vf_splat(r29, 1);
  r22 = gc_vf_mul(r26, r40);
  r31 = gc_vf_add(r30, r29);
  r41 = gc_vf_splat(r27, 0);
  r32 = gc_vf_sub(r29, r41);
  r42 = gc_vf_splat(r30, 1);
  r33 = gc_vf_mul(r26, r42);
  r16 = gc_q2g(r29);
  r43 = gc_vf_splat(r27, 0);
  r34 = gc_vf_sub(r31, r43);
  r18 = gc_q2g(r31);
  r44 = r18;
  r45 = r16;
  r45 = r45 & r44;
  r46 = r45;
  r22 = gc_vf_sub(r28, r22);
  r47 = 0x0ull;
  r48 = gc_stl;
  if ((s64)r46 >= (s64)r47)
    goto L49;
  r49 = ((u64)(u32)(gc_stl + 8));
  r48 = r49;
L49:;
  r50 = r48;
  r33 = gc_vf_sub(r24, r33);
  r52 = gc_stl;
  if (r50 == r52)
    goto L56;
  r53 = ((u64)(u32)(gc_stl + -10));
  goto L161;
  goto L57;
L56:;
  r51 = gc_stl;
L57:;
  r17 = gc_q2g(r32);
  r19 = gc_q2g(r34);
  r54 = r17;
  r55 = r19;
  r54 = r54 | r55;
  r56 = r54;
  r57 = 0x0ull;
  r58 = gc_stl;
  if ((s64)r56 < (s64)r57)
    goto L70;
  r59 = ((u64)(u32)(gc_stl + 8));
  r58 = r59;
L70:;
  r60 = r58;
  r62 = gc_stl;
  if (r60 == r62)
    goto L77;
  r63 = ((u64)(u32)(gc_stl + -10));
  goto L161;
  goto L78;
L77:;
  r61 = gc_stl;
L78:;
  r64 = gc_goal_ptr(&gc_stack[0]);
  r65 = gc_goal_ptr(&gc_stack[2]);
  r66 = r64;
  r67 = r65;
  gc_st_v128(r66, 0, r22);
  gc_st_v128(r67, 0, r33);
  r68 = gc_ld_u32(gc_stl, GC_SYMOFF(0));
  r70 = r12;
  r71 = r66;
  r72 = r67;
  r73 = r68;
  r69 = ((u64(*)(u64, u64, u64))gc_fn(r73))(r70, r71, r72);
  r74 = r69;
  r75 = gc_g2f(r74);
  r76 = r75;
  r77 = gc_f2g(r76);
  r78 = 0x0ull;
  r79 = gc_stl;
  if ((s64)r77 >= (s64)r78)
    goto L101;
  r80 = ((u64)(u32)(gc_stl + 8));
  r79 = r80;
L101:;
  r81 = r79;
  r35 = gc_f2q(r75);
  r83 = gc_stl;
  if (r81 == r83)
    goto L108;
  r84 = ((u64)(u32)(gc_stl + -10));
  goto L161;
  goto L109;
L108:;
  r82 = gc_stl;
L109:;
  r85 = gc_vf_splat(r35, 0);
  r30 = gc_vf_mul(r30, r85);
  r29 = gc_vf_add(r29, r30);
  r86 = gc_vf_splat(r29, 1);
  r26 = gc_vf_mul(r26, r86);
  r87 = gc_vf_splat(r27, 0);
  r32 = gc_vf_sub(r29, r87);
  r20 = gc_q2g(r29);
  r88 = r20;
  r89 = 0x0ull;
  r90 = gc_stl;
  if ((s64)r88 >= (s64)r89)
    goto L124;
  r91 = ((u64)(u32)(gc_stl + 8));
  r90 = r91;
L124:;
  r92 = r90;
  r93 = gc_vf_add(r25, r26);
  r25 = gc_vf_blend(r25, r93, 7);
  r95 = gc_stl;
  if (r92 == r95)
    goto L132;
  r96 = ((u64)(u32)(gc_stl + -10));
  goto L161;
  goto L133;
L132:;
  r94 = gc_stl;
L133:;
  r21 = gc_q2g(r32);
  r97 = r21;
  r98 = 0x0ull;
  r99 = gc_stl;
  if ((s64)r97 < (s64)r98)
    goto L141;
  r100 = ((u64)(u32)(gc_stl + 8));
  r99 = r100;
L141:;
  r101 = r99;
  gc_st_v128(r14, 0, r25);
  r103 = gc_stl;
  if (r101 == r103)
    goto L148;
  r104 = ((u64)(u32)(gc_stl + -10));
  goto L161;
  goto L149;
L148:;
  r102 = gc_stl;
L149:;
  r105 = ((u64)(u32)(gc_stl + 8));
  r106 = r105;
  r15 = r75;
  r108 = gc_stl;
  if (r106 == r108)
    goto L158;
  r109 = ((u64)(u32)(gc_stl + -10));
  goto L163;
  goto L159;
L158:;
  r107 = gc_stl;
L159:;
L161:;
  r110 = gc_ld_f32(gc_sb, 192 + 0);
  r15 = r110;
L163:;
  r111 = gc_f2g(r15);
  r7 = r111;
  return r7;
}

static u64 gc_f6(u64 a0, u64 a1, u64 a2, u64 a3) {
  u8* const gc_mb = goalc_mem;
  const u64 gc_stl = (u32)goalc_st;
  const u64 gc_sb = GC_SEG(0);
  u64 r0 = 0;
  u64 r1 = 0;
  u64 r2 = 0;
  u64 r3 = 0;
  u64 r4 = 0;
  u64 r5 = 0;
  u64 r6 = 0;
  u64 r7 = 0;
  u64 r8 = 0;
  u64 r9 = 0;
  float r10 = 0;
  float r11 = 0;
  float r12 = 0;
  u64 r13 = 0;
  u64 r14 = 0;
  u64 r15 = 0;
  u64 r16 = 0;
  u64 r17 = 0;
  u64 r18 = 0;
  u64 r19 = 0;
  float r20 = 0;
  u64 r21 = 0;
  float r22 = 0;
  u64 r23 = 0;
  u64 r24 = 0;
  u64 r25 = 0;
  u64 r26 = 0;
  u64 r27 = 0;
  v128 r28 = {0};
  u64 r29 = 0;
  u64 r30 = 0;
  u64 r31 = 0;
  u64 r32 = 0;
  v128 r33 = {0};
  v128 r34 = {0};
  v128 r35 = {0};
  v128 r36 = {0};
  float r37 = 0;
  u64 r38 = 0;
  u64 r39 = 0;
  u64 r40 = 0;
  u64 r41 = 0;
  u64 r42 = 0;
  u64 r43 = 0;
  u64 r44 = 0;
  u64 r45 = 0;
  u64 r46 = 0;
  u64 r47 = 0;
  u64 r48 = 0;
  u64 r49 = 0;
  u64 r50 = 0;
  u64 r51 = 0;
  u64 r52 = 0;
  u64 r53 = 0;
  u64 r54 = 0;
  u64 r55 = 0;
  v128 r56 = {0};
  v128 r57 = {0};
  v128 r58 = {0};
  v128 r59 = {0};
  u64 r60 = 0;
  u64 gc_stack[2] __attribute__((aligned(16)));
  r0 = a0;
  r1 = a1;
  r2 = a2;
  r3 = a3;
  r5 = r0;
  r6 = r1;
  r7 = r2;
  r8 = r3;
  r9 = gc_ld_u32(gc_stl, GC_SYMOFF(1));
  r11 = gc_ld_f32(r5, 12);
  r10 = r11;
  r12 = gc_ld_f32(r7, 12);
  r10 = r10 + r12;
  r14 = r5;
  r15 = r6;
  r16 = r7;
  r17 = gc_f2g(r10);
  r18 = r9;
  r13 = ((u64(*)(u64, u64, u64, u64))gc_fn(r18))(r14, r15, r16, r17);
  r19 = r13;
  r20 = gc_g2f(r19);
  r22 = gc_ld_f32(gc_sb, 316 + 0);
  if (r20 < r22)
    goto L66;
  r23 = gc_ld_u32(gc_stl, GC_SYMOFF(2));
  r24 = gc_goal_ptr(&gc_stack[0]);
  r25 = r24;
  r26 = 0x0ull;
  r27 = r26;
  r28 = gc_g2q(r27);
  gc_st_v128(r25, 0, r28);
  r29 = r25;
  r30 = r7;
  r31 = r5;
  r35 = gc_ld_v128(r30, 0);
  r36 = gc_ld_v128(r31, 0);
  r33 = gc_ld_v128(gc_sb, 320 + 0);
  r34 = gc_vf_sub(r35, r36);
  r34 = gc_vf_blend(r34, r33, 8);
  gc_st_v128(r29, 0, r34);
  r37 = gc_ld_f32(r5, 12);
  r39 = r29;
  r40 = gc_f2g(r37);
  r41 = r23;
  r38 = ((u64(*)(u64, u64))gc_fn(r41))(r39, r40);
  r42 = r38;
  r43 = r42;
  r44 = gc_ld_u32(gc_stl, GC_SYMOFF(3));
  r46 = r8;
  r47 = r5;
  r48 = r6;
  r49 = gc_f2g(r20);
  r50 = r44;
  r45 = ((u64(*)(u64, u64, u64, u64))gc_fn(r50))(r46, r47, r48, r49);
  r51 = r45;
  r52 = r8;
  r53 = r8;
  r54 = r43;
  r58 = gc_ld_v128(r53, 0);
  r59 = gc_ld_v128(r54, 0);
  r56 = gc_ld_v128(gc_sb, 336 + 0);
  r57 = gc_vf_add(r58, r59);
  r57 = gc_vf_blend(r57, r56, 8);
  gc_st_v128(r52, 0, r57);
  r21 = r52;
  goto L67;
L66:;
  r21 = gc_stl;
L67:;
  r60 = gc_f2g(r20);
  r4 = r60;
  return r4;
}

static const uint8_t gc_seg0[352] = {
    0xae, 0xae, 0xae, 0xae, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00,
    0xae, 0xae, 0xae, 0xae, 0xff, 0xff, 0xff, 0xff, 0x01, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00,
    0xae, 0xae, 0xae, 0xae, 0xff, 0xff, 0xff, 0xff, 0x02, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00,
    0xae, 0xae, 0xae, 0xae, 0xff, 0xff, 0xff, 0xff, 0x03, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00,
    0xae, 0xae, 0xae, 0xae, 0xff, 0xff, 0xff, 0xff, 0x04, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00,
    0xae, 0xae, 0xae, 0xae, 0xff, 0xff, 0xff, 0xff, 0x05, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00,
    0xae, 0xae, 0xae, 0xae, 0xff, 0xff, 0xff, 0xff, 0x06, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3f,
    0x00, 0x00, 0x80, 0x3f, 0x20, 0xbc, 0xbe, 0xcc, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3f,
    0x00, 0x00, 0x80, 0x3f, 0x20, 0xbc, 0xbe, 0xcc, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3f,
    0x20, 0xbc, 0xbe, 0xcc, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3f,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0xbc, 0xbe, 0xcc, 0x00, 0x00, 0x00, 0x00,
    0xbe, 0xbe, 0xbe, 0xbe, 0x15, 0x00, 0x00, 0x00, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x64, 0x65, 0x2d,
    0x64, 0x6f, 0x2d, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x73, 0x00, 0x00, 0x00,
    0xbe, 0xbe, 0xbe, 0xbe, 0x20, 0x00, 0x00, 0x00, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x2d, 0x73,
    0x70, 0x68, 0x65, 0x72, 0x65, 0x2d, 0x74, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x2d, 0x69,
    0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3f,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3f,
};

static const GoalcRefFunc gc_ref_funcs[4] = {
    {"pc-port-raw-ray-sphere-implementation", 20, 3, (void*)gc_f1},
    {"ray-sphere-intersect", 36, 4, (void*)gc_f2},
    {"ray-cylinder-intersect", 68, 7, (void*)gc_f4},
    {"moving-sphere-sphere-intersect", 100, 4, (void*)gc_f6},
};

const GoalcRefModule goalc_ref_collide_func = {
    "collide-func", 12, gc_sym_names, gc_sym_offsets, gc_seg_base, gc_seg0, 352, 4, gc_ref_funcs};
