#!/usr/bin/env python3
# (AI-assisted)
"""
Extracts GOAL functions compiled to C by goalc (--instruction-set c) into test fixtures: the
reference versions of GOAL functions that have a native replacement (see goalc_ref.h).

  extract.py CSRC_DIR OBJ_DIR OUT_DIR

CSRC_DIR / OBJ_DIR: out/jak1/csrc and out/jak1/obj of a project built with
  goalc --game jak1 --instruction-set c -c '(make-group "all-code")'

For every module in MODULES, writes OUT_DIR/<module>.c with the module's symbol table, the
requested functions (verbatim) and the bytes of its main segment (constants), from the object file.

The GOAL functions that have a native version are def-mips2c in goal_src, with their GOAL code in a
#| |# comment next to it: to regenerate their fixtures, compile with those defuns put back.
"""

import os
import re
import shutil
import struct
import subprocess
import sys

# module -> GOAL functions (defuns) to extract
MODULES = {
    "collide-func": [
        "pc-port-raw-ray-sphere-implementation",
        "ray-sphere-intersect",
        "ray-cylinder-intersect",
        "moving-sphere-sphere-intersect",
    ],
    "geometry": [
        "vector-segment-distance-point!",
        "closest-pt-in-triangle",
    ],
    "vector": [
        "vector+*!",
        "vector-length",
        "vector-normalize!",
    ],
}


def c_ident(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def segment0(obj_path):
    """bytes of segment 0 (main) of a v3 GOAL object file"""
    data = open(obj_path, "rb").read()
    assert data[:4] == b"GOAL", obj_path
    version, segcount = struct.unpack_from("<II", data, 8)
    assert version == 3 and segcount == 3, (version, segcount)
    # link_infos[3] (offset, size) at 16, code_infos[3] at 40, link_block_length at 64
    code_off, code_size = struct.unpack_from("<II", data, 40)
    (link_block_length,) = struct.unpack_from("<I", data, 64)
    start = link_block_length + code_off
    return data[start:start + code_size]


def functions(src):
    """gc_fN -> source text"""
    out = {}
    for m in re.finditer(r"^static (?:u64|v128) gc_f(\d+)\(.*?^}\n", src, re.S | re.M):
        out[int(m.group(1))] = m.group(0)
    return out


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(2)
    csrc, obj_dir, out_dir = sys.argv[1:]
    for mod, wanted in MODULES.items():
        src = open(os.path.join(csrc, mod + ".c")).read()
        seg = segment0(os.path.join(obj_dir, mod + ".o"))
        names_m = re.search(r"static const char\* const gc_sym_names\[(\d+)\] = \{\n(.*?)\n\};", src,
                            re.S)
        n_syms = int(names_m.group(1))
        sym_names = re.findall(r'^  ("(?:[^"\\]|\\.)*"),$', names_m.group(2), re.M)
        assert len(sym_names) == n_syms, mod
        hash_m = re.search(r"static const GoalCModule gc_module = \{\n  (0x[0-9a-f]+)ull", src)
        # the top level binds each defun: rN = GC_SEG_ADDR(0, stub + 4); symbol <- rN
        binds = {}
        for r, off, k in re.findall(
                r"(r\d+) = GC_SEG_ADDR\(0, (\d+)\);\n  gc_st_u32\(gc_stl, GC_SYMOFF\((\d+)\), \1\);",
                src):
            binds[sym_names[int(k)][1:-1]] = int(off)
        funcs = functions(src)
        entries = []
        body = []
        for name in wanted:
            off = binds[name]  # function value: segment offset of the stub + 4
            (tag,) = struct.unpack_from("<I", seg, off + 4)
            assert tag & 0x80000000, (mod, name, hex(tag))
            idx = tag & 0x7fffffff
            arity = len(re.findall(r"u64 a\d+", funcs[idx].split("{", 1)[0]))
            entries.append((name, off, idx, arity))
            body.append(funcs[idx])
        lines = [
            "// (AI-assisted) Generated by test/mips2c_native/goalc_ref/extract.py: do not edit.",
            f"// GOAL module {mod} compiled to C by goalc (--instruction-set c, module hash "
            f"{hash_m.group(1) if hash_m else '?'}),",
            "// only the functions the tests use, and the module's main segment.",
            '#include "goal_c_ops.h"',
            '#include "goalc_ref.h"',
            "",
            '_Static_assert(GOALC_ABI_VERSION == 2, "regenerate the fixtures (extract.py)");',
            "",
            f"static int32_t gc_sym_offsets[{n_syms}];",
            "static uint32_t gc_seg_base[3];",
            f"static const char* const gc_sym_names[{n_syms}] = {{",
        ]
        lines += [f"  {s}," for s in sym_names]
        lines += ["};", ""]
        lines += body
        lines.append(f"static const uint8_t gc_seg0[{len(seg)}] = {{")
        for i in range(0, len(seg), 16):
            lines.append("  " + " ".join(f"0x{b:02x}," for b in seg[i:i + 16]))
        lines += ["};", ""]
        lines.append(f"static const GoalcRefFunc gc_ref_funcs[{len(entries)}] = {{")
        for name, off, idx, arity in entries:
            lines.append(f'  {{"{name}", {off}, {arity}, (void*)gc_f{idx}}},')
        lines += ["};", ""]
        lines.append(f"const GoalcRefModule goalc_ref_{c_ident(mod)} = {{")
        lines.append(f'  "{mod}", {n_syms}, gc_sym_names, gc_sym_offsets, gc_seg_base, gc_seg0, '
                     f"{len(seg)}, {len(entries)}, gc_ref_funcs}};")
        path = os.path.join(out_dir, c_ident(mod) + ".c")
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")
        # like the rest of test/ (task format), so formatting doesn't change the fixtures
        if shutil.which("clang-format"):
            subprocess.run(["clang-format", "-i", "--style=file", path], check=True)
        print(f"{path}: {', '.join(e[0] for e in entries)}")


if __name__ == "__main__":
    main()
