#pragma once

/*!
 * @file goalc_ref.h
 * (AI-assisted)
 * GOAL functions compiled to C by goalc, used as the reference versions of GOAL functions that
 * have a native replacement (the replacement must give the same results as the code the 3DS runs
 * in C mode). The fixtures (<module>.c) are generated by extract.py from goalc's output and loaded
 * into the harness's GOAL memory by goalc_ref.cpp.
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct GoalcRefFunc {
  const char* name;  //! the symbol the module's top level sets to this function
  uint32_t value;    //! the function value: offset of its stub in segment 0, + 4
  uint32_t arity;    //! number of arguments
  void* fn;          //! the host function
} GoalcRefFunc;

typedef struct GoalcRefModule {
  const char* name;
  uint32_t n_syms;
  const char* const* sym_names;
  int32_t* sym_offsets;  //! filled by the loader: symbol address - goalc_st
  uint32_t* seg_base;    //! filled by the loader: GOAL address of segment 0, others 0
  const uint8_t* seg0;   //! contents of segment 0 (stubs and constants)
  uint32_t seg0_size;
  uint32_t n_funcs;
  const GoalcRefFunc* funcs;
} GoalcRefModule;

#ifdef __cplusplus
}
#endif
