#pragma once

/*!
 * @file goal_c_ops.h
 * Helpers used by C code generated by goalc (--instruction-set c).
 * Each helper reproduces the behavior of the native (x86-64) backend exactly, including
 * edge cases like out of range float to int conversions and shift amounts.
 */

#include <math.h>
#include <stdint.h>
#include <string.h>

#include "goal_c_abi.h"

typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int8_t s8;
typedef int16_t s16;
typedef int32_t s32;
typedef int64_t s64;
//! 128-bit values in generated code: four floats, so the compiler can keep them in (VFP/SIMD)
//! registers. Same size, layout and alignment as goalc_v128 (lane 0 = x = lowest address).
//! Integer views go through gc_m128 (a union, which lives in memory: only used by the less common
//! 128-bit integer ops and mixed-class registers).
typedef struct {
  float x, y, z, w;
} v128;
typedef union {
  v128 v;
  goalc_v128 u;
} gc_m128;
_Static_assert(sizeof(v128) == 16, "v128 size");

#define GC_INLINE static inline __attribute__((always_inline))

// ---------------------------------------------------------------------------
// memory. GOAL addresses are 32 bits: truncate before adding the host base.
// Alignment: accesses use memcpy, and on 32-bit ARM the compiler may still use LDRD/VLDR, which
// need word alignment. That is fine for GOAL: the EE (MIPS) requires natural alignment for 32/64
// bit and float loads/stores, so the game never does unaligned accesses of those sizes. (Forcing
// byte-safe accesses with packed structs roughly doubled ARM11 code size.)
// ---------------------------------------------------------------------------

GC_INLINE u8* gc_addr(u64 goal_addr) {
  return goalc_mem + (u32)goal_addr;
}

GC_INLINE u64 gc_ld_u8(u64 a) {
  return *gc_addr(a);
}
GC_INLINE u64 gc_ld_s8(u64 a) {
  return (u64)(s64)(s8)*gc_addr(a);
}
GC_INLINE u64 gc_ld_u16(u64 a) {
  u16 v;
  memcpy(&v, gc_addr(a), 2);
  return v;
}
GC_INLINE u64 gc_ld_s16(u64 a) {
  s16 v;
  memcpy(&v, gc_addr(a), 2);
  return (u64)(s64)v;
}
GC_INLINE u64 gc_ld_u32(u64 a) {
  u32 v;
  memcpy(&v, gc_addr(a), 4);
  return v;
}
GC_INLINE u64 gc_ld_s32(u64 a) {
  s32 v;
  memcpy(&v, gc_addr(a), 4);
  return (u64)(s64)v;
}
GC_INLINE u64 gc_ld_u64(u64 a) {
  u64 v;
  memcpy(&v, gc_addr(a), 8);
  return v;
}
GC_INLINE float gc_ld_f32(u64 a) {
  float v;
  memcpy(&v, gc_addr(a), 4);
  return v;
}
GC_INLINE v128 gc_ld_v128(u64 a) {
  v128 v;
  memcpy(&v, gc_addr(a), 16);
  return v;
}

GC_INLINE void gc_st_u8(u64 a, u64 v) {
  *gc_addr(a) = (u8)v;
}
GC_INLINE void gc_st_u16(u64 a, u64 v) {
  u16 x = (u16)v;
  memcpy(gc_addr(a), &x, 2);
}
GC_INLINE void gc_st_u32(u64 a, u64 v) {
  u32 x = (u32)v;
  memcpy(gc_addr(a), &x, 4);
}
GC_INLINE void gc_st_u64(u64 a, u64 v) {
  memcpy(gc_addr(a), &v, 8);
}
GC_INLINE void gc_st_f32(u64 a, float v) {
  memcpy(gc_addr(a), &v, 4);
}
GC_INLINE void gc_st_v128(u64 a, v128 v) {
  memcpy(gc_addr(a), &v, 16);
}

//! GOAL address of a host pointer (only valid for pointers into GOAL memory, like the stack).
//! The empty asm makes the pointer escape: otherwise, on 32-bit hosts, the compiler can see that
//! goalc_mem + result is the original pointer, conclude that stack arrays are never accessed
//! through GOAL addresses, and delete stores to them.
GC_INLINE u64 gc_goal_ptr(const void* host) {
  const u8* p = (const u8*)host;
  __asm__ volatile("" : "+r"(p) : : "memory");
  return (u64)(u32)(p - goalc_mem);
}

// ---------------------------------------------------------------------------
// register class conversions (regset_common in IR.cpp)
// ---------------------------------------------------------------------------

//! float -> gpr: 32-bit pattern, sign extended (movd + movsx)
GC_INLINE u64 gc_f2g(float f) {
  s32 v;
  memcpy(&v, &f, 4);
  return (u64)(s64)v;
}
//! gpr -> float: low 32 bits
GC_INLINE float gc_g2f(u64 g) {
  u32 v = (u32)g;
  float f;
  memcpy(&f, &v, 4);
  return f;
}
GC_INLINE u32 gc_fbits(float f) {
  u32 u;
  memcpy(&u, &f, 4);
  return u;
}
GC_INLINE float gc_bitsf(u32 u) {
  float f;
  memcpy(&f, &u, 4);
  return f;
}
//! gpr -> 128: low 64 bits, upper cleared (movq)
GC_INLINE v128 gc_g2q(u64 g) {
  v128 r = {gc_bitsf((u32)g), gc_bitsf((u32)(g >> 32)), 0.f, 0.f};
  return r;
}
//! float -> 128: lane 0
GC_INLINE v128 gc_f2q(float f) {
  v128 r = {f, 0.f, 0.f, 0.f};
  return r;
}
GC_INLINE u64 gc_q2g(v128 q) {
  return (u64)gc_fbits(q.x) | ((u64)gc_fbits(q.y) << 32);
}
GC_INLINE float gc_q2f(v128 q) {
  return q.x;
}
GC_INLINE goalc_v128 gc_mu(v128 v) {
  gc_m128 m;
  m.v = v;
  return m.u;
}
GC_INLINE v128 gc_um(goalc_v128 u) {
  gc_m128 m;
  m.u = u;
  return m.v;
}

// ---------------------------------------------------------------------------
// integer math
// ---------------------------------------------------------------------------

GC_INLINE u64 gc_imul32(u64 a, u64 b) {
  return (u64)(s64)(s32)((u32)a * (u32)b);
}
GC_INLINE u64 gc_imul64(u64 a, u64 b) {
  return a * b;
}
GC_INLINE u64 gc_idiv32(u64 a, u64 b) {
  s32 x = (s32)a, y = (s32)b;
  if (y == 0) {
    return 0;
  }
  if (y == -1) {
    return (u64)(s64)(s32)(0u - (u32)x);
  }
  return (u64)(s64)(x / y);
}
GC_INLINE u64 gc_imod32(u64 a, u64 b) {
  s32 x = (s32)a, y = (s32)b;
  if (y == 0 || y == -1) {
    return 0;
  }
  return (u64)(s64)(x % y);
}
GC_INLINE u64 gc_udiv32(u64 a, u64 b) {
  u32 x = (u32)a, y = (u32)b;
  if (y == 0) {
    return 0;
  }
  return (u64)(s64)(s32)(x / y);
}
GC_INLINE u64 gc_umod32(u64 a, u64 b) {
  u32 x = (u32)a, y = (u32)b;
  if (y == 0) {
    return 0;
  }
  return (u64)(s64)(s32)(x % y);
}
// variable shifts use the low 6 bits of the shift amount (x86 and ARM64 agree)
GC_INLINE u64 gc_shl(u64 a, u64 s) {
  return a << (s & 63);
}
GC_INLINE u64 gc_shr(u64 a, u64 s) {
  return a >> (s & 63);
}
GC_INLINE u64 gc_sar(u64 a, u64 s) {
  return (u64)((s64)a >> (s & 63));
}

// ---------------------------------------------------------------------------
// float math
// ---------------------------------------------------------------------------

//! float to int32, truncating and saturating like the EE (CVT.W.S) and the ARM64 backend.
//! NaN gives 0 (the EE has no NaNs, ARM64 gives 0).
GC_INLINE s32 gc_cvtt(float f) {
  if (f != f) {
    return 0;
  }
  if (f >= 2147483648.0f) {
    return INT32_MAX;
  }
  if (f <= -2147483648.0f) {
    return INT32_MIN;
  }
  return (s32)f;
}
GC_INLINE u64 gc_f2i(float f) {
  return (u64)(s64)gc_cvtt(f);
}
GC_INLINE float gc_i2f(u64 i) {
  return (float)(s32)i;
}
// minss / maxss: return the second operand if either is NaN.
GC_INLINE float gc_fmin(float a, float b) {
  return a < b ? a : b;
}
GC_INLINE float gc_fmax(float a, float b) {
  return a > b ? a : b;
}

// ---------------------------------------------------------------------------
// vector float (lane-wise)
// ---------------------------------------------------------------------------

#define GC_EACH(OP) OP(x) OP(y) OP(z) OP(w)
#define GC_LANEWISE2(name, EXPR)       \
  GC_INLINE v128 name(v128 a, v128 b) { \
    v128 r;                             \
    GC_EACH(EXPR)                       \
    return r;                           \
  }
#define GC_ADD(l) r.l = a.l + b.l;
#define GC_SUB(l) r.l = a.l - b.l;
#define GC_MUL(l) r.l = a.l * b.l;
#define GC_DIV(l) r.l = a.l / b.l;
#define GC_MIN(l) r.l = a.l < b.l ? a.l : b.l;
#define GC_MAX(l) r.l = a.l > b.l ? a.l : b.l;
#define GC_XOR(l) r.l = gc_bitsf(gc_fbits(a.l) ^ gc_fbits(b.l));
GC_LANEWISE2(gc_vf_add, GC_ADD)
GC_LANEWISE2(gc_vf_sub, GC_SUB)
GC_LANEWISE2(gc_vf_mul, GC_MUL)
GC_LANEWISE2(gc_vf_div, GC_DIV)
GC_LANEWISE2(gc_vf_min, GC_MIN)
GC_LANEWISE2(gc_vf_max, GC_MAX)
GC_LANEWISE2(gc_vf_xor, GC_XOR)

GC_INLINE v128 gc_vf_sqrt(v128 a) {
  v128 r = {__builtin_sqrtf(a.x), __builtin_sqrtf(a.y), __builtin_sqrtf(a.z),
            __builtin_sqrtf(a.w)};
  return r;
}
GC_INLINE v128 gc_vf_ftoi(v128 a) {
  v128 r = {gc_bitsf((u32)gc_cvtt(a.x)), gc_bitsf((u32)gc_cvtt(a.y)),
            gc_bitsf((u32)gc_cvtt(a.z)), gc_bitsf((u32)gc_cvtt(a.w))};
  return r;
}
GC_INLINE v128 gc_vf_itof(v128 a) {
  v128 r = {(float)(s32)gc_fbits(a.x), (float)(s32)gc_fbits(a.y), (float)(s32)gc_fbits(a.z),
            (float)(s32)gc_fbits(a.w)};
  return r;
}
//! blendps: mask bit i set takes lane i from b
GC_INLINE v128 gc_vf_blend(v128 a, v128 b, u32 mask) {
  v128 r = {(mask & 1) ? b.x : a.x, (mask & 2) ? b.y : a.y, (mask & 4) ? b.z : a.z,
            (mask & 8) ? b.w : a.w};
  return r;
}
//! lane by index (the index is a constant in generated code, so this folds away)
GC_INLINE float gc_lane(v128 a, u32 lane) {
  switch (lane & 3) {
    case 0:
      return a.x;
    case 1:
      return a.y;
    case 2:
      return a.z;
    default:
      return a.w;
  }
}
GC_INLINE v128 gc_vf_splat(v128 a, u32 lane) {
  float f = gc_lane(a, lane);
  v128 r = {f, f, f, f};
  return r;
}
//! shufps a, a, ctrl: lane i = a[(ctrl >> 2i) & 3]
GC_INLINE v128 gc_vf_swizzle(v128 a, u32 ctrl) {
  v128 r = {gc_lane(a, ctrl), gc_lane(a, ctrl >> 2), gc_lane(a, ctrl >> 4), gc_lane(a, ctrl >> 6)};
  return r;
}

// ---------------------------------------------------------------------------
// 128-bit integer (PS2 MMI), MIPS operand order: rd = op(rs = a, rt = b)
// ---------------------------------------------------------------------------

#define GC_U_LANES(expr)        \
  goalc_v128 r;                 \
  for (int i = 0; i < 4; i++) { \
    expr;                       \
  }                             \
  return r;


GC_INLINE goalc_v128 gc_pextlb_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  for (int i = 0; i < 8; i++) {
    r.du8[2 * i] = t.du8[i];
    r.du8[2 * i + 1] = s.du8[i];
  }
  return r;
}
GC_INLINE goalc_v128 gc_pextub_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  for (int i = 0; i < 8; i++) {
    r.du8[2 * i] = t.du8[8 + i];
    r.du8[2 * i + 1] = s.du8[8 + i];
  }
  return r;
}
GC_INLINE goalc_v128 gc_pextlh_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  for (int i = 0; i < 4; i++) {
    r.du16[2 * i] = t.du16[i];
    r.du16[2 * i + 1] = s.du16[i];
  }
  return r;
}
GC_INLINE goalc_v128 gc_pextuh_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  for (int i = 0; i < 4; i++) {
    r.du16[2 * i] = t.du16[4 + i];
    r.du16[2 * i + 1] = s.du16[4 + i];
  }
  return r;
}
GC_INLINE goalc_v128 gc_pextlw_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  r.du32[0] = t.du32[0];
  r.du32[1] = s.du32[0];
  r.du32[2] = t.du32[1];
  r.du32[3] = s.du32[1];
  return r;
}
GC_INLINE goalc_v128 gc_pextuw_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  r.du32[0] = t.du32[2];
  r.du32[1] = s.du32[2];
  r.du32[2] = t.du32[3];
  r.du32[3] = s.du32[3];
  return r;
}
GC_INLINE goalc_v128 gc_pcpyld_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  r.du64[0] = t.du64[0];
  r.du64[1] = s.du64[0];
  return r;
}
GC_INLINE goalc_v128 gc_pcpyud_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  r.du64[0] = s.du64[1];
  r.du64[1] = t.du64[1];
  return r;
}
GC_INLINE goalc_v128 gc_psubw_u(goalc_v128 s, goalc_v128 t) {
  GC_U_LANES(r.du32[i] = s.du32[i] - t.du32[i])
}
GC_INLINE goalc_v128 gc_pceqb_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = s.du8[i] == t.du8[i] ? 0xff : 0;
  }
  return r;
}
GC_INLINE goalc_v128 gc_pceqh_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  for (int i = 0; i < 8; i++) {
    r.du16[i] = s.du16[i] == t.du16[i] ? 0xffff : 0;
  }
  return r;
}
GC_INLINE goalc_v128 gc_pceqw_u(goalc_v128 s, goalc_v128 t) {
  GC_U_LANES(r.du32[i] = s.du32[i] == t.du32[i] ? 0xffffffffu : 0)
}
GC_INLINE goalc_v128 gc_pcgtb_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = s.ds8[i] > t.ds8[i] ? 0xff : 0;
  }
  return r;
}
GC_INLINE goalc_v128 gc_pcgth_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  for (int i = 0; i < 8; i++) {
    r.du16[i] = s.ds16[i] > t.ds16[i] ? 0xffff : 0;
  }
  return r;
}
GC_INLINE goalc_v128 gc_pcgtw_u(goalc_v128 s, goalc_v128 t) {
  GC_U_LANES(r.du32[i] = s.ds32[i] > t.ds32[i] ? 0xffffffffu : 0)
}
GC_INLINE goalc_v128 gc_por_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  r.du64[0] = s.du64[0] | t.du64[0];
  r.du64[1] = s.du64[1] | t.du64[1];
  return r;
}
GC_INLINE goalc_v128 gc_pxor_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  r.du64[0] = s.du64[0] ^ t.du64[0];
  r.du64[1] = s.du64[1] ^ t.du64[1];
  return r;
}
GC_INLINE goalc_v128 gc_pand_u(goalc_v128 s, goalc_v128 t) {
  goalc_v128 r;
  r.du64[0] = s.du64[0] & t.du64[0];
  r.du64[1] = s.du64[1] & t.du64[1];
  return r;
}
GC_INLINE u8 gc_sat_u8(s16 x) {
  return x < 0 ? 0 : (x > 255 ? 255 : (u8)x);
}
//! vpackuswb a, b: signed halfwords of a -> bytes 0-7, of b -> bytes 8-15, unsigned saturation
GC_INLINE goalc_v128 gc_packuswb_u(goalc_v128 a, goalc_v128 b) {
  goalc_v128 r;
  for (int i = 0; i < 8; i++) {
    r.du8[i] = gc_sat_u8(a.ds16[i]);
    r.du8[8 + i] = gc_sat_u8(b.ds16[i]);
  }
  return r;
}
GC_INLINE goalc_v128 gc_paddb_u(goalc_v128 a, goalc_v128 b) {
  goalc_v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = (u8)(a.du8[i] + b.du8[i]);
  }
  return r;
}
// shifts by immediate, x86 semantics: logical shifts >= width give 0, arithmetic gives sign fill
GC_INLINE goalc_v128 gc_pw_sll_u(goalc_v128 a, u32 s) {
  GC_U_LANES(r.du32[i] = s > 31 ? 0 : a.du32[i] << s)
}
GC_INLINE goalc_v128 gc_pw_srl_u(goalc_v128 a, u32 s) {
  GC_U_LANES(r.du32[i] = s > 31 ? 0 : a.du32[i] >> s)
}
GC_INLINE goalc_v128 gc_pw_sra_u(goalc_v128 a, u32 s) {
  GC_U_LANES(r.ds32[i] = a.ds32[i] >> (s > 31 ? 31 : s))
}
GC_INLINE goalc_v128 gc_ph_sll_u(goalc_v128 a, u32 s) {
  goalc_v128 r;
  for (int i = 0; i < 8; i++) {
    r.du16[i] = s > 15 ? 0 : (u16)(a.du16[i] << s);
  }
  return r;
}
GC_INLINE goalc_v128 gc_ph_srl_u(goalc_v128 a, u32 s) {
  goalc_v128 r;
  for (int i = 0; i < 8; i++) {
    r.du16[i] = s > 15 ? 0 : (u16)(a.du16[i] >> s);
  }
  return r;
}
//! vpsrldq: shift the whole register right by s bytes
GC_INLINE goalc_v128 gc_psrldq_u(goalc_v128 a, u32 s) {
  goalc_v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = (i + s < 16) ? a.du8[i + s] : 0;
  }
  return r;
}
//! vpslldq: shift the whole register left by s bytes
GC_INLINE goalc_v128 gc_pslldq_u(goalc_v128 a, u32 s) {
  goalc_v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = (i >= (int)s) ? a.du8[i - s] : 0;
  }
  return r;
}
//! vpshuflw: shuffle the low 4 halfwords, copy the high 4
GC_INLINE goalc_v128 gc_pshuflw_u(goalc_v128 a, u32 c) {
  goalc_v128 r = a;
  for (int i = 0; i < 4; i++) {
    r.du16[i] = a.du16[(c >> (2 * i)) & 3];
  }
  return r;
}
//! vpshufhw: shuffle the high 4 halfwords, copy the low 4
GC_INLINE goalc_v128 gc_pshufhw_u(goalc_v128 a, u32 c) {
  goalc_v128 r = a;
  for (int i = 0; i < 4; i++) {
    r.du16[4 + i] = a.du16[4 + ((c >> (2 * i)) & 3)];
  }
  return r;
}


// wrappers taking the register representation
GC_INLINE v128 gc_pextlb(v128 s, v128 t) {
  return gc_um(gc_pextlb_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pextub(v128 s, v128 t) {
  return gc_um(gc_pextub_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pextlh(v128 s, v128 t) {
  return gc_um(gc_pextlh_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pextuh(v128 s, v128 t) {
  return gc_um(gc_pextuh_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pextlw(v128 s, v128 t) {
  return gc_um(gc_pextlw_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pextuw(v128 s, v128 t) {
  return gc_um(gc_pextuw_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pcpyld(v128 s, v128 t) {
  return gc_um(gc_pcpyld_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pcpyud(v128 s, v128 t) {
  return gc_um(gc_pcpyud_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_psubw(v128 s, v128 t) {
  return gc_um(gc_psubw_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pceqb(v128 s, v128 t) {
  return gc_um(gc_pceqb_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pceqh(v128 s, v128 t) {
  return gc_um(gc_pceqh_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pceqw(v128 s, v128 t) {
  return gc_um(gc_pceqw_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pcgtb(v128 s, v128 t) {
  return gc_um(gc_pcgtb_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pcgth(v128 s, v128 t) {
  return gc_um(gc_pcgth_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pcgtw(v128 s, v128 t) {
  return gc_um(gc_pcgtw_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_por(v128 s, v128 t) {
  return gc_um(gc_por_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pxor(v128 s, v128 t) {
  return gc_um(gc_pxor_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_pand(v128 s, v128 t) {
  return gc_um(gc_pand_u(gc_mu(s), gc_mu(t)));
}
GC_INLINE v128 gc_packuswb(v128 a, v128 b) {
  return gc_um(gc_packuswb_u(gc_mu(a), gc_mu(b)));
}
GC_INLINE v128 gc_paddb(v128 a, v128 b) {
  return gc_um(gc_paddb_u(gc_mu(a), gc_mu(b)));
}
GC_INLINE v128 gc_pw_sll(v128 a, u32 s) {
  return gc_um(gc_pw_sll_u(gc_mu(a), s));
}
GC_INLINE v128 gc_pw_srl(v128 a, u32 s) {
  return gc_um(gc_pw_srl_u(gc_mu(a), s));
}
GC_INLINE v128 gc_pw_sra(v128 a, u32 s) {
  return gc_um(gc_pw_sra_u(gc_mu(a), s));
}
GC_INLINE v128 gc_ph_sll(v128 a, u32 s) {
  return gc_um(gc_ph_sll_u(gc_mu(a), s));
}
GC_INLINE v128 gc_ph_srl(v128 a, u32 s) {
  return gc_um(gc_ph_srl_u(gc_mu(a), s));
}
GC_INLINE v128 gc_psrldq(v128 a, u32 s) {
  return gc_um(gc_psrldq_u(gc_mu(a), s));
}
GC_INLINE v128 gc_pslldq(v128 a, u32 s) {
  return gc_um(gc_pslldq_u(gc_mu(a), s));
}
GC_INLINE v128 gc_pshuflw(v128 a, u32 c) {
  return gc_um(gc_pshuflw_u(gc_mu(a), c));
}
GC_INLINE v128 gc_pshufhw(v128 a, u32 c) {
  return gc_um(gc_pshufhw_u(gc_mu(a), c));
}

// ---------------------------------------------------------------------------
// module support
// ---------------------------------------------------------------------------

//! Address of symbol k's value slot relative to st (jak 1: symbol value is at the symbol).
#define GC_SYM(k) (goalc_st + (u64)(s64)gc_sym_offsets[k])
#define GC_SEG(s) ((u64)gc_seg_base[s])
//! address in another segment of this object: 0 if that segment isn't loaded (like the native
//! linker), so method-set! of a function in an unloaded debug segment does nothing.
#define GC_SEG_ADDR(s, off) (gc_seg_base[s] ? (u64)gc_seg_base[s] + (u64)(off) : 0)
