#pragma once

/*!
 * @file goal_c_ops.h
 * Helpers used by C code generated by goalc (--instruction-set c).
 * Each helper reproduces the behavior of the native (x86-64) backend exactly, including
 * edge cases like out of range float to int conversions and shift amounts.
 */

#include <math.h>
#include <stdint.h>
#include <string.h>

#include "goal_c_abi.h"

typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int8_t s8;
typedef int16_t s16;
typedef int32_t s32;
typedef int64_t s64;
typedef goalc_v128 v128;

#define GC_INLINE static inline __attribute__((always_inline))

// ---------------------------------------------------------------------------
// memory. GOAL addresses are 32 bits: truncate before adding the host base.
// ---------------------------------------------------------------------------

GC_INLINE u8* gc_addr(u64 goal_addr) {
  return goalc_mem + (u32)goal_addr;
}

GC_INLINE u64 gc_ld_u8(u64 a) {
  return *gc_addr(a);
}
GC_INLINE u64 gc_ld_s8(u64 a) {
  return (u64)(s64)(s8)*gc_addr(a);
}
GC_INLINE u64 gc_ld_u16(u64 a) {
  u16 v;
  memcpy(&v, gc_addr(a), 2);
  return v;
}
GC_INLINE u64 gc_ld_s16(u64 a) {
  s16 v;
  memcpy(&v, gc_addr(a), 2);
  return (u64)(s64)v;
}
GC_INLINE u64 gc_ld_u32(u64 a) {
  u32 v;
  memcpy(&v, gc_addr(a), 4);
  return v;
}
GC_INLINE u64 gc_ld_s32(u64 a) {
  s32 v;
  memcpy(&v, gc_addr(a), 4);
  return (u64)(s64)v;
}
GC_INLINE u64 gc_ld_u64(u64 a) {
  u64 v;
  memcpy(&v, gc_addr(a), 8);
  return v;
}
GC_INLINE float gc_ld_f32(u64 a) {
  float v;
  memcpy(&v, gc_addr(a), 4);
  return v;
}
GC_INLINE v128 gc_ld_v128(u64 a) {
  v128 v;
  memcpy(&v, gc_addr(a), 16);
  return v;
}

GC_INLINE void gc_st_u8(u64 a, u64 v) {
  *gc_addr(a) = (u8)v;
}
GC_INLINE void gc_st_u16(u64 a, u64 v) {
  u16 x = (u16)v;
  memcpy(gc_addr(a), &x, 2);
}
GC_INLINE void gc_st_u32(u64 a, u64 v) {
  u32 x = (u32)v;
  memcpy(gc_addr(a), &x, 4);
}
GC_INLINE void gc_st_u64(u64 a, u64 v) {
  memcpy(gc_addr(a), &v, 8);
}
GC_INLINE void gc_st_f32(u64 a, float v) {
  memcpy(gc_addr(a), &v, 4);
}
GC_INLINE void gc_st_v128(u64 a, v128 v) {
  memcpy(gc_addr(a), &v, 16);
}

//! GOAL address of a host pointer (only valid for pointers into GOAL memory, like the stack).
GC_INLINE u64 gc_goal_ptr(const void* host) {
  return (u64)(u32)((const u8*)host - goalc_mem);
}

// ---------------------------------------------------------------------------
// register class conversions (regset_common in IR.cpp)
// ---------------------------------------------------------------------------

//! float -> gpr: 32-bit pattern, sign extended (movd + movsx)
GC_INLINE u64 gc_f2g(float f) {
  s32 v;
  memcpy(&v, &f, 4);
  return (u64)(s64)v;
}
//! gpr -> float: low 32 bits
GC_INLINE float gc_g2f(u64 g) {
  u32 v = (u32)g;
  float f;
  memcpy(&f, &v, 4);
  return f;
}
//! gpr -> 128: low 64 bits, upper cleared (movq)
GC_INLINE v128 gc_g2q(u64 g) {
  v128 r;
  r.du64[0] = g;
  r.du64[1] = 0;
  return r;
}
//! float -> 128: lane 0
GC_INLINE v128 gc_f2q(float f) {
  v128 r;
  r.du64[0] = 0;
  r.du64[1] = 0;
  r.f[0] = f;
  return r;
}
GC_INLINE u64 gc_q2g(v128 q) {
  return q.du64[0];
}
GC_INLINE float gc_q2f(v128 q) {
  return q.f[0];
}

// ---------------------------------------------------------------------------
// integer math
// ---------------------------------------------------------------------------

GC_INLINE u64 gc_imul32(u64 a, u64 b) {
  return (u64)(s64)(s32)((u32)a * (u32)b);
}
GC_INLINE u64 gc_imul64(u64 a, u64 b) {
  return a * b;
}
GC_INLINE u64 gc_idiv32(u64 a, u64 b) {
  s32 x = (s32)a, y = (s32)b;
  if (y == 0) {
    return 0;
  }
  if (y == -1) {
    return (u64)(s64)(s32)(0u - (u32)x);
  }
  return (u64)(s64)(x / y);
}
GC_INLINE u64 gc_imod32(u64 a, u64 b) {
  s32 x = (s32)a, y = (s32)b;
  if (y == 0 || y == -1) {
    return 0;
  }
  return (u64)(s64)(x % y);
}
GC_INLINE u64 gc_udiv32(u64 a, u64 b) {
  u32 x = (u32)a, y = (u32)b;
  if (y == 0) {
    return 0;
  }
  return (u64)(s64)(s32)(x / y);
}
GC_INLINE u64 gc_umod32(u64 a, u64 b) {
  u32 x = (u32)a, y = (u32)b;
  if (y == 0) {
    return 0;
  }
  return (u64)(s64)(s32)(x % y);
}
// variable shifts use the low 6 bits of the shift amount (x86 and ARM64 agree)
GC_INLINE u64 gc_shl(u64 a, u64 s) {
  return a << (s & 63);
}
GC_INLINE u64 gc_shr(u64 a, u64 s) {
  return a >> (s & 63);
}
GC_INLINE u64 gc_sar(u64 a, u64 s) {
  return (u64)((s64)a >> (s & 63));
}

// ---------------------------------------------------------------------------
// float math
// ---------------------------------------------------------------------------

//! float to int32, truncating and saturating like the EE (CVT.W.S) and the ARM64 backend.
//! NaN gives 0 (the EE has no NaNs, ARM64 gives 0).
GC_INLINE s32 gc_cvtt(float f) {
  if (f != f) {
    return 0;
  }
  if (f >= 2147483648.0f) {
    return INT32_MAX;
  }
  if (f <= -2147483648.0f) {
    return INT32_MIN;
  }
  return (s32)f;
}
GC_INLINE u64 gc_f2i(float f) {
  return (u64)(s64)gc_cvtt(f);
}
GC_INLINE float gc_i2f(u64 i) {
  return (float)(s32)i;
}
// minss / maxss: return the second operand if either is NaN.
GC_INLINE float gc_fmin(float a, float b) {
  return a < b ? a : b;
}
GC_INLINE float gc_fmax(float a, float b) {
  return a > b ? a : b;
}

// ---------------------------------------------------------------------------
// vector float (lane-wise)
// ---------------------------------------------------------------------------

#define GC_VF_LANES(expr)       \
  v128 r;                       \
  for (int i = 0; i < 4; i++) { \
    expr;                       \
  }                             \
  return r;

GC_INLINE v128 gc_vf_add(v128 a, v128 b) {
  GC_VF_LANES(r.f[i] = a.f[i] + b.f[i])
}
GC_INLINE v128 gc_vf_sub(v128 a, v128 b) {
  GC_VF_LANES(r.f[i] = a.f[i] - b.f[i])
}
GC_INLINE v128 gc_vf_mul(v128 a, v128 b) {
  GC_VF_LANES(r.f[i] = a.f[i] * b.f[i])
}
GC_INLINE v128 gc_vf_div(v128 a, v128 b) {
  GC_VF_LANES(r.f[i] = a.f[i] / b.f[i])
}
GC_INLINE v128 gc_vf_min(v128 a, v128 b) {
  GC_VF_LANES(r.f[i] = a.f[i] < b.f[i] ? a.f[i] : b.f[i])
}
GC_INLINE v128 gc_vf_max(v128 a, v128 b) {
  GC_VF_LANES(r.f[i] = a.f[i] > b.f[i] ? a.f[i] : b.f[i])
}
GC_INLINE v128 gc_vf_xor(v128 a, v128 b) {
  GC_VF_LANES(r.du32[i] = a.du32[i] ^ b.du32[i])
}
GC_INLINE v128 gc_vf_sqrt(v128 a) {
  GC_VF_LANES(r.f[i] = sqrtf(a.f[i]))
}
GC_INLINE v128 gc_vf_ftoi(v128 a) {
  GC_VF_LANES(r.ds32[i] = gc_cvtt(a.f[i]))
}
GC_INLINE v128 gc_vf_itof(v128 a) {
  GC_VF_LANES(r.f[i] = (float)a.ds32[i])
}
//! blendps: mask bit i set takes lane i from b
GC_INLINE v128 gc_vf_blend(v128 a, v128 b, u32 mask) {
  GC_VF_LANES(r.du32[i] = ((mask >> i) & 1) ? b.du32[i] : a.du32[i])
}
GC_INLINE v128 gc_vf_splat(v128 a, u32 lane) {
  GC_VF_LANES(r.du32[i] = a.du32[lane])
}
//! shufps a, a, ctrl: lane i = a[(ctrl >> 2i) & 3]
GC_INLINE v128 gc_vf_swizzle(v128 a, u32 ctrl) {
  GC_VF_LANES(r.du32[i] = a.du32[(ctrl >> (2 * i)) & 3])
}

// ---------------------------------------------------------------------------
// 128-bit integer (PS2 MMI), MIPS operand order: rd = op(rs = a, rt = b)
// ---------------------------------------------------------------------------

GC_INLINE v128 gc_pextlb(v128 s, v128 t) {
  v128 r;
  for (int i = 0; i < 8; i++) {
    r.du8[2 * i] = t.du8[i];
    r.du8[2 * i + 1] = s.du8[i];
  }
  return r;
}
GC_INLINE v128 gc_pextub(v128 s, v128 t) {
  v128 r;
  for (int i = 0; i < 8; i++) {
    r.du8[2 * i] = t.du8[8 + i];
    r.du8[2 * i + 1] = s.du8[8 + i];
  }
  return r;
}
GC_INLINE v128 gc_pextlh(v128 s, v128 t) {
  v128 r;
  for (int i = 0; i < 4; i++) {
    r.du16[2 * i] = t.du16[i];
    r.du16[2 * i + 1] = s.du16[i];
  }
  return r;
}
GC_INLINE v128 gc_pextuh(v128 s, v128 t) {
  v128 r;
  for (int i = 0; i < 4; i++) {
    r.du16[2 * i] = t.du16[4 + i];
    r.du16[2 * i + 1] = s.du16[4 + i];
  }
  return r;
}
GC_INLINE v128 gc_pextlw(v128 s, v128 t) {
  v128 r;
  r.du32[0] = t.du32[0];
  r.du32[1] = s.du32[0];
  r.du32[2] = t.du32[1];
  r.du32[3] = s.du32[1];
  return r;
}
GC_INLINE v128 gc_pextuw(v128 s, v128 t) {
  v128 r;
  r.du32[0] = t.du32[2];
  r.du32[1] = s.du32[2];
  r.du32[2] = t.du32[3];
  r.du32[3] = s.du32[3];
  return r;
}
GC_INLINE v128 gc_pcpyld(v128 s, v128 t) {
  v128 r;
  r.du64[0] = t.du64[0];
  r.du64[1] = s.du64[0];
  return r;
}
GC_INLINE v128 gc_pcpyud(v128 s, v128 t) {
  v128 r;
  r.du64[0] = s.du64[1];
  r.du64[1] = t.du64[1];
  return r;
}
GC_INLINE v128 gc_psubw(v128 s, v128 t) {
  GC_VF_LANES(r.du32[i] = s.du32[i] - t.du32[i])
}
GC_INLINE v128 gc_pceqb(v128 s, v128 t) {
  v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = s.du8[i] == t.du8[i] ? 0xff : 0;
  }
  return r;
}
GC_INLINE v128 gc_pceqh(v128 s, v128 t) {
  v128 r;
  for (int i = 0; i < 8; i++) {
    r.du16[i] = s.du16[i] == t.du16[i] ? 0xffff : 0;
  }
  return r;
}
GC_INLINE v128 gc_pceqw(v128 s, v128 t) {
  GC_VF_LANES(r.du32[i] = s.du32[i] == t.du32[i] ? 0xffffffffu : 0)
}
GC_INLINE v128 gc_pcgtb(v128 s, v128 t) {
  v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = s.ds8[i] > t.ds8[i] ? 0xff : 0;
  }
  return r;
}
GC_INLINE v128 gc_pcgth(v128 s, v128 t) {
  v128 r;
  for (int i = 0; i < 8; i++) {
    r.du16[i] = s.ds16[i] > t.ds16[i] ? 0xffff : 0;
  }
  return r;
}
GC_INLINE v128 gc_pcgtw(v128 s, v128 t) {
  GC_VF_LANES(r.du32[i] = s.ds32[i] > t.ds32[i] ? 0xffffffffu : 0)
}
GC_INLINE v128 gc_por(v128 s, v128 t) {
  v128 r;
  r.du64[0] = s.du64[0] | t.du64[0];
  r.du64[1] = s.du64[1] | t.du64[1];
  return r;
}
GC_INLINE v128 gc_pxor(v128 s, v128 t) {
  v128 r;
  r.du64[0] = s.du64[0] ^ t.du64[0];
  r.du64[1] = s.du64[1] ^ t.du64[1];
  return r;
}
GC_INLINE v128 gc_pand(v128 s, v128 t) {
  v128 r;
  r.du64[0] = s.du64[0] & t.du64[0];
  r.du64[1] = s.du64[1] & t.du64[1];
  return r;
}
GC_INLINE u8 gc_sat_u8(s16 x) {
  return x < 0 ? 0 : (x > 255 ? 255 : (u8)x);
}
//! vpackuswb a, b: signed halfwords of a -> bytes 0-7, of b -> bytes 8-15, unsigned saturation
GC_INLINE v128 gc_packuswb(v128 a, v128 b) {
  v128 r;
  for (int i = 0; i < 8; i++) {
    r.du8[i] = gc_sat_u8(a.ds16[i]);
    r.du8[8 + i] = gc_sat_u8(b.ds16[i]);
  }
  return r;
}
GC_INLINE v128 gc_paddb(v128 a, v128 b) {
  v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = (u8)(a.du8[i] + b.du8[i]);
  }
  return r;
}
// shifts by immediate, x86 semantics: logical shifts >= width give 0, arithmetic gives sign fill
GC_INLINE v128 gc_pw_sll(v128 a, u32 s) {
  GC_VF_LANES(r.du32[i] = s > 31 ? 0 : a.du32[i] << s)
}
GC_INLINE v128 gc_pw_srl(v128 a, u32 s) {
  GC_VF_LANES(r.du32[i] = s > 31 ? 0 : a.du32[i] >> s)
}
GC_INLINE v128 gc_pw_sra(v128 a, u32 s) {
  GC_VF_LANES(r.ds32[i] = a.ds32[i] >> (s > 31 ? 31 : s))
}
GC_INLINE v128 gc_ph_sll(v128 a, u32 s) {
  v128 r;
  for (int i = 0; i < 8; i++) {
    r.du16[i] = s > 15 ? 0 : (u16)(a.du16[i] << s);
  }
  return r;
}
GC_INLINE v128 gc_ph_srl(v128 a, u32 s) {
  v128 r;
  for (int i = 0; i < 8; i++) {
    r.du16[i] = s > 15 ? 0 : (u16)(a.du16[i] >> s);
  }
  return r;
}
//! vpsrldq: shift the whole register right by s bytes
GC_INLINE v128 gc_psrldq(v128 a, u32 s) {
  v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = (i + s < 16) ? a.du8[i + s] : 0;
  }
  return r;
}
//! vpslldq: shift the whole register left by s bytes
GC_INLINE v128 gc_pslldq(v128 a, u32 s) {
  v128 r;
  for (int i = 0; i < 16; i++) {
    r.du8[i] = (i >= (int)s) ? a.du8[i - s] : 0;
  }
  return r;
}
//! vpshuflw: shuffle the low 4 halfwords, copy the high 4
GC_INLINE v128 gc_pshuflw(v128 a, u32 c) {
  v128 r = a;
  for (int i = 0; i < 4; i++) {
    r.du16[i] = a.du16[(c >> (2 * i)) & 3];
  }
  return r;
}
//! vpshufhw: shuffle the high 4 halfwords, copy the low 4
GC_INLINE v128 gc_pshufhw(v128 a, u32 c) {
  v128 r = a;
  for (int i = 0; i < 4; i++) {
    r.du16[4 + i] = a.du16[4 + ((c >> (2 * i)) & 3)];
  }
  return r;
}

// ---------------------------------------------------------------------------
// module support
// ---------------------------------------------------------------------------

//! Address of symbol k's value slot relative to st (jak 1: symbol value is at the symbol).
#define GC_SYM(k) (goalc_st + (u64)(s64)gc_sym_offsets[k])
#define GC_SEG(s) ((u64)gc_seg_base[s])
//! address in another segment of this object: 0 if that segment isn't loaded (like the native
//! linker), so method-set! of a function in an unloaded debug segment does nothing.
#define GC_SEG_ADDR(s, off) (gc_seg_base[s] ? (u64)gc_seg_base[s] + (u64)(off) : 0)
