#!/usr/bin/env python3
"""
Generate the registry of statically linked GOAL C modules (see docs/3ds-port/c_backend.md).

goalc --instruction-set c writes one C file per object to out/<game>/csrc/. When those files are
compiled with -DGOALC_STATIC, each exports goalc_static_<name>(). This script writes a C file with
goalc_register_static_modules(), which registers all of them with the runtime.

usage: gen_c_registry.py <csrc dir> <output .c file>
"""

import os
import re
import sys


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    csrc, out_path = sys.argv[1], sys.argv[2]
    pattern = re.compile(r"^const GoalCModule\* (goalc_static_\w+)\(void\) \{", re.MULTILINE)
    names = []
    for file_name in sorted(os.listdir(csrc)):
        if not file_name.endswith(".c"):
            continue
        with open(os.path.join(csrc, file_name)) as f:
            match = pattern.search(f.read())
        if not match:
            print(f"warning: {file_name} has no static module accessor")
            continue
        names.append(match.group(1))

    lines = [
        "// Generated by scripts/3ds/gen_c_registry.py. Do not edit.",
        '#include "goal_c_abi.h"',
        "",
    ]
    lines += [f"const GoalCModule* {n}(void);" for n in names]
    lines += ["", "void goalc_register_static_modules(void) {"]
    lines += [f"  goalc_register_module({n}());" for n in names]
    lines += ["}", ""]
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"{len(names)} modules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
